using System;  // using System;
using System.Collections.Generic;  // using System.Collections.Generic;
using System.Linq;  // using System.Linq;
using System.Text;  // using System.Text;
using System.Threading.Tasks;  // using System.Threading.Tasks;
// Espacio entre líneas;
namespace _6_2.CruzBetancourtVictorManuel  // Nombre de la práctica;
{  // Se abre la llave;
    class Menú  // Se crea la clase Menú;
    {  // Se abre la llave;
        public void MenúBúsqueda()  // Se declara un método público que no regresa valores que lleva por nombre MenúBúsqueda(); 
        {  // Se abre la llave;
            Búsqueda BB = new Búsqueda();  // Se crea un objeto de la clase Búsqueda que lleva por nombre BB;
            // Espacio entre líneas;
            string Opc = "0";  // Se declara una variable de tipo string que lleva por nombre Opc y se inicializa en "0";
            do  // Se crea un ciclo do while;
            {  // Se abre la llave;
                Console.Clear();  // Se limpia lo que hay en la consola;
                string MenúPrincipal = "==========Instituto Tecnológico de Tijuana==========\n===========Cruz Betancourt Victor Manuel============\n================Estructura de Datos=================\n=================Búsqueda Binaria==================\n\nSeleccione alguna de las siguientes opciones.\n1) Ejemplo 1\n2) Ejemplo 2\n3) Salir";  // Se declara una variable de tipo string que lleva por nombre MenúPrincipal y tiene un valor en ella;
                Console.WriteLine(MenúPrincipal);  // Se imprime el mensaje indicado en la variable MenúPrincipal y se genera un salto de línea;
                Opc = Console.ReadLine();  // Se lee lo ingresado por el usuario y se le asigna a la variable Opc;
                switch (Opc)  // Se crea uun Switch; 
                {  // Se abre la llave;
                    case "1":  // Caso "1";
                        Console.Clear();  // Se limpia lo que hay en la consola;
                        Console.WriteLine("==========Instituto Tecnológico de Tijuana==========\n===========Cruz Betancourt Victor Manuel============\n================Estructura de Datos=================\n=================Búsqueda Binaria==================\n");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
                        BB.Ejemplo1();  // Se manda a llamar al método llamado Ejemplo1 de la clase Búsqueda por medio del objeto BB;
                        Console.ReadKey();  // Se genera una pausa en el programa;
                        break;  // Break;
                        // Espacio entre código;
                    case "2":  // Caso "2";
                        Console.Clear();  // Se limpia lo que hay en la consola;
                        Console.WriteLine("==========Instituto Tecnológico de Tijuana==========\n===========Cruz Betancourt Victor Manuel============\n================Estructura de Datos=================\n=================Búsqueda Binaria==================\n");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
                        BB.Ejemplo2();  // Se manda a llamar al método llamado Ejemplo2 de la clase Búsqueda por medio del objeto BB;
                        Console.ReadKey();  // Se genera una pausa en el programa;
                        break;  // Break;
                        // Espacio entre código;
                    case "3":  // Caso "3";
                        return;  // Sale del programa;
                        // Espacio entre código;
                    default:  // Default;
                        Console.WriteLine("Escoge un número correcto");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
                        break;  // Break;
                }  // Se cierra la llave;
            } while (Opc != "3");  // Mientras Opc sea diferente de "3";
            Console.ReadKey();  // Se genera una pausa en el programa;
        }  // Se cierra la llave;
    }  // Se cierra la llave;
}  // Se cierra la llave;