using System;  // using System;
using System.Collections.Generic;  // using System.Collections.Generic;
using System.Linq;  // using System.Linq;
using System.Text;  // using System.Text;
using System.Threading.Tasks;  // using System.Threading.Tasks;
// Espacio entre líneas;
namespace _6_1.CruzBetancourtVictorManuel  // Nombre de la práctica;
{  // Se abre la llave;
    class Búsqueda  // Se crea la clase Búsqueda;
    {  // Se abre la llave;
        public bool BusquedaSecuencial(int Elemento, List<int> Lista)  // Se crea un método de tipo bool, que lleva por nombre BusquedaSecuencial y que lleva consigo dos parámetros sobrecargados;
        {  // Se abre la llave;
            int Tamaño = Lista.Count;  // Se declara una variable de tio int, que lleva por nombre Tamaño, la cual se iguala al numero de elementos que hay en la Lista;
            int Posicion = 0;  // Se declara una variable de tipo int, que lleva por nombre Posicion, la cual es inicializada en 0;
            while (Posicion < Tamaño)  // Se crea un ciclo while que se ejecuta, siempre y cuando la Posicion sea menor que el Tamaño;
            {  // Se abre la llave;
                if (Lista[Posicion] == Elemento)  // Se crea un ciclo if que compara si la Lista[Posicion] es igual al Elemento;
                {  // Se abre la llave;
                    return true;  // Retorna true;
                }  // Se cierra la llave;
                else  // Sino;
                {  // Se abre la llave;
                    Posicion++;  // La variable Posicion incrementa 1 en su valor;
                }  // Se cierra la llave;
            }  // Se cierra la llave;
            return false;  // Retorna false;
        }  // Se cierra la llave;
    }  // Se cierra la llave;
}  // Se cierra la llave;
