using System;  // using System;
using System.Collections.Generic;  // using System.Collections.Generic;
using System.Linq;  // using System.Linq;
using System.Text;  // using System.Text;
using System.Threading.Tasks;  // using System.Threading.Tasks;
// Espacio entre líneas;
namespace _6_1.CruzBetancourtVictorManuel  // Nombre de la práctica;
{  // Se abre la llave;
    class CapturaDatos  // Se crea la clase CapturaDatos;
    {  // Se abre la llave;
        public void Ejemplo1()  // Se crea un método público que no regresa valores, que lleva por nombre Ejemplo1;
        {  // Se abre la llave;
            Búsqueda Bus = new Búsqueda();  // Se crea un objeto de la clase Búsqueda, que lleva por nombre Bus;
            // Espacio entre líneas;
            List<int> Lista = new List<int>();  // Se crea una lista de tipo int, que lleva por nombre Lista;
            // Espacio entre líneas;
            Lista.Add(20);  // Se añade el elemento 20 a la lista;
            Lista.Add(11);  // Se añade el elemento 11 a la lista;
            Lista.Add(24);  // Se añade el elemento 24 a la lista;
            Lista.Add(15);  // Se añade el elemento 15 a la lista;
            Lista.Add(3);  // Se añade el elemento 3 a la lista;
            Lista.Add(2);  // Se añade el elemento 2 a la lista;
            Lista.Add(-6);  // Se añade el elemento -6 a la lista;
            Lista.Add(7);  // Se añade el elemento 7 a la lista;
            Console.WriteLine("Método de Búsqueda Secuencial\nEjemplo 1\n");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            Console.WriteLine("Los números presentes en la lista son los siguientes: ");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            foreach (var item in Lista)  // Se crea un ciclo foreach, en donde se declara una variable que recibe los valores contenidos en la Lista;
            {  // Se abre la llave;
                Console.WriteLine(item);  // Se imprimen en la consola los valores de la variable item y se genera un salto de línea;
            }  // Se cierra la llave;
            Console.WriteLine("\n¿Qué elemento desea buscar en la lista?");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            int Elemento = int.Parse(Console.ReadLine());  // Se lee lo que ingrese el usuario y se guarda en la variable Elemento;
            Console.WriteLine();  // Se genera un salto de línea;
            Console.WriteLine("¿El elemento {0} se encuentra en la Lista? \n", Elemento);  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            if (Bus.BusquedaSecuencial(Elemento, Lista) == true)  // Se crea una ciclo if que indica si el elemento esta en la lista o no;
            {  // Se abre la llave
                Console.WriteLine("¡Felicitaciones! El elemento que usted busca si se encuentrá en la lista :)");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            }  // Se cierra la llave;
            else  // Sino;
            {  // Se abre la llave;
                Console.WriteLine("¡Mejor suerte para la próxima! El elemento que usted busca no se encuentra en la lista :(");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            }  // Se cierra la llave;
            Console.ReadKey();  // Se genera una pausa en el programa;
        }  // Se cierra la llave;
        // Espacio entre líneas;
        public void Ejemplo2()  // Se crea un método público que no regresa valores, que lleva por nombre Ejemplo2;
        {  // Se abre la llave;
            Búsqueda Bus = new Búsqueda();  // Se crea un objeto de la clase Búsqueda, que lleva por nombre Bus;
            // Espacio entre líneas;
            List<int> Lista = new List<int>();  // Se crea una lista de tipo int, que lleva por nombre Lista;
            // Espacio entre líneas;
            Lista.Add(45);  // Se añade el elemento 45 a la lista;
            Lista.Add(32);  // Se añade el elemento 32 a la lista;
            Lista.Add(123);  // Se añade el elemento 123 a la lista;
            Lista.Add(9823);  // Se añade el elemento 9823 a la lista;
            Lista.Add(45);  // Se añade el elemento 45 a la lista;
            Lista.Add(1);  // Se añade el elemento 1 a la lista;
            Lista.Add(76);  // Se añade el elemento 76 a la lista;
            Lista.Add(200);  // Se añade el elemento 200 a la lista;
            // Espacio entre líneas;
            Console.WriteLine("Método de Búsqueda Secuencial\nEjemplo 2\n");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            Console.WriteLine("Los números presentes en la lista son los siguientes: ");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            foreach (var item in Lista)  // Se crea un ciclo foreach, en donde se declara una variable que recibe los valores contenidos en la Lista;
            {  // Se abre la llave;
                Console.WriteLine(item);  // Se imprimen en la consola los valores de la variable item y se genera un salto de línea;
            }  // Se cierra la llave;
            Console.WriteLine("\n¿Qué elemento desea buscar en la lista?");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            int Elemento = int.Parse(Console.ReadLine());  // Se lee lo que ingrese el usuario y se guarda en la variable Elemento;
            Console.WriteLine();  // Se genera un salto de línea;
            Console.WriteLine("¿El elemento {0} se encuentra en la Lista? \n", Elemento);  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            if (Bus.BusquedaSecuencial(Elemento, Lista) == true)  // Se crea una ciclo if que indica si el elemento esta en la lista o no;
            {  // Se abre la llave;
                Console.WriteLine("¡Felicitaciones! El elemento que usted busca si se encuentrá en la lista :)");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            }  // Se cierra la llave;
            else  // Sino;
            {  // Se abre la llave;
                Console.WriteLine("¡Mejor suerte para la próxima! El elemento que usted busca no se encuentra en la lista :(");  // Se imprime el mensaje indicado en la consola y se genera un salto de línea;
            }  // Se cierra la llave;
            Console.ReadKey();  // Se genera una pausa en el programa;
        }  // Se cierra la llave;
    }  // Se cierra la llave;
}  // Se cierra la llave;
