using System;  // using System;
using System.Collections.Generic;  // using System.Collections.Generic;
using System.Linq;  // using System.Linq;
using System.Text;  // using System.Text;
using System.Threading.Tasks;  // using System.Threading.Tasks;
// Espacio entre líneas;
namespace _6_1.CruzBetancourtVictorManuel  // Nombre de la práctica;
{  // Se abre la llave;
    class Program  // Clase Program;
    {  // Se abre la llave;
        static void Main(string[] args)  // Clase Main;
        {  // Se abre la llave;
            CapturaDatos CapDat = new CapturaDatos();  // // Se crea un objeto de la clase CapturaDatos, que lleva por nombre CapDat;
            CapDat.Ejemplo1();  // Se manda a llamar al método Ejemplo1, por medio del objeto CapDat;
            Console.Clear();  // Se limpia la pantalla;
            CapDat.Ejemplo2();  // Se manda a llamar al método Ejemplo2, por medio del objeto CapDat;
        }  // Se cierra la llave;
    }  // Se cierra la llave;
}  // Se cierra la llave;
